### ISSUE TITLE
Improved error message: "The pyaload is invalid"

### ISSUE THREAD

**Issue by yungookim** [Typeform/js-api-client#79]
## Description
I've received the below error without much detail when calling `forms.create`.
```
Error: The payload is invalid.
>      at /Users/fooboo/Deploy/Agentnoon/node_modules/@typeform/api-client/dist/index.cjs.js:3663:27
>      at processTicksAndRejections (internal/process/task_queues.js:95:5)
>      at async /Users/fooboo/Deploy/Agentnoon/functions/node_modules/firebase-functions/lib/common/providers/https.js:385:26
>      at async runFunction (/Users/fooboo/.nvm/versions/node/v14.18.1/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:533:9)
>      at async runHTTPS (/Users/fooboo/.nvm/versions/node/v14.18.1/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:559:5)
>      at async handler (/Users/fooboo/.nvm/versions/node/v14.18.1/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:479:17)
```

Turns out, my workspace property was incorrect. But it'd have been nice if the API provided more details on which part of the payload is incorrect.

Thanks!
Dave

**Comment by mathio** [comment]
I agree. Closing in favor of #56 that has more details.
