### ISSUE TITLE
Typeform API client not compatible with Cloudflare workers / Vercel edge runtime

### ISSUE THREAD

**Issue by magnuslundin** [Typeform/js-api-client#94]
The current version of the Typeform API client does not run well on a Cloudflare worker / Vercel edge runtime. Creating a client result in the following error:

```
ReferenceError: window is not defined
    at (../../../../node_modules/.pnpm/@typeform+api-client@1.8.0/node_modules/@typeform/api-client/dist/typeform-api.js:1:209)
    at (../../../../node_modules/.pnpm/@typeform+api-client@1.8.0/node_modules/@typeform/api-client/dist/typeform-api.js:1:68)
    at (../../../../node_modules/.pnpm/@typeform+api-client@1.8.0/node_modules/@typeform/api-client/dist/typeform-api.js:1:170)
...
```

This is most probably caused by the (3 year old..) dependency to Axios. A switch to fetch should not only resolve the compatibility issue, but render the project free from build dependencies.

**Comment by mathio** [comment]
Hello @magnuslundin 

can you please show us how you are using the library? How do you import it? The `dist/typeform-api.js` file is intended to be used in a browser, not server-side which might be causing your issue.

**Comment by magnuslundin** [comment]
> Hello @magnuslundin
> 
> can you please show us how you are using the library? How do you import it? The `dist/typeform-api.js` file is intended to be used in a browser, not server-side which might be causing your issue.
> 
> Also, the axios dependency was updated recently. Please try with the latest version of the lib.

I'm using the library in a SvelteKit project deployed on Vercel. By default is SvelteKit deciding how the rendering occur, on the server side or not. In my case did the import fail in SSR-mode.

To circumvent this am I currently ensuring that the import is not done in SSR:
```javascript
let typeform;
onMount(async () => {
    typeform = await import('@typeform/embed');
});
```
This works, but I prefer to let SvelteKit decide how to render the page.

Nice that the dependency is updated. I'll give it a go.

**Comment by mathio** [comment]
Please let us know if the problem still remains.

**Comment by mathio** [comment]
I just noticed you mentioned a different Typeform library - [Embed SDK](https://github.com/Typeform/embed). This library is not intended to be used server side. However when used with eg. NextJS it should render an empty div server-side and populate it with the embed (iframe with your typeform) when rendered client side - see [React NextJS demos](https://github.com/Typeform/embed-demo#react-nextjs).

If the issue persists please [raise it in embed SDK](https://github.com/Typeform/embed/issues) with details.

**Comment by mathio** [comment]
Thank you. I dont have much experience with Cloudflare workers, but I can test with Vercel.

**Comment by teamclouday** [comment]
I'm getting the same error on nextjs server side. Is there an API client for server side?

**Comment by magnuslundin** [comment]
> I'm getting the same error on nextjs server side. Is there an API client for server side?

No, there isn't. We have to make due creating our own implementations from this:
https://www.typeform.com/developers/responses/

**Comment by teamclouday** [comment]
> > I'm getting the same error on nextjs server side. Is there an API client for server side?
> 
> No, there isn't. We have to make due creating our own implementations from this: https://www.typeform.com/developers/responses/

Thank you! I was able to make it work by using fetch calls to the API directly, and cast the response to the types defined in this library.
